### PR TITLE
feat: support individual dbs

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by sblaisot** [comment]
I can see how this could help when dealing with temporary db creation, but, as far as I understand it, in the second part, the original database will get destroyed/recreated and I'm afraid couch-continuum will be unable to recreate it with the same name starting with `_` right ?

**Comment by janl** [comment]
@sblaisot the system databases are whitelisted to be re-created with an underscore.

**Comment by sblaisot** [comment]
Do you plan to merge this soon and release a new version on npm containing this fix ?

**Comment by janl** [comment]
here you go ;)

**Comment by garbados** [comment]
Published in 2.2.0

**Pull request merged**
